name: Licenses
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-licenses:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps: 
    - name: Licenses and permissions
      with:
        filename: metrics.plugin.licenses.svg
        token: ${{ secrets.LICENSE_TOKEN }}
        base: ""
        template: repository
        repo: metrics
        plugin_licenses: yes
        plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'

    - name: Licenses with open-source ratio graphs
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.licenses.ratio.svg
        token: ${{ secrets.LICENSE_TOKEN }}
        base: ""
        template: repository
        repo: metrics
        plugin_licenses: yes
        plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
        plugin_licenses_legal: no
        plugin_licenses_ratio: yes
